Задание 1 - подскажите правильно ли реализовал dict comprehension?

In [49]:
import requests

def valute_name():
    r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')
    response = r.json()['Valute']
    my_dic = {}
    max_list = [];
    for k,v in response.items(): 
        my_dic.setdefault(k,v['Value'])
        max_list.append(v['Value'])
    
    maximum = max(max_list) 
    
    return {k for k,v in my_dic.items() if v == maximum}
    
    
#     for k,v in my_dic.items():
#         if v == maximum:
#             return k;

In [50]:
valute_name()

"{'XDR'}"

Задание 2 - немного сомневаюьс правильно ли понял условие задачи,а именно "Считайте, self.diff будет принимать значение True только при возврате значения курса."

In [15]:
class Rate:
    def __init__(self, format_='value', diff_ = False):
        self.format = format_
        self.diff = diff_
    
    def exchange_rates(self):
        self.r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')
        return self.r.json()['Valute']
    
    def make_format(self, currency):
        response = self.exchange_rates()
        
        if currency in response:
            if self.format == 'full':
                return response[currency]
            if  self.format == 'value' and self.diff == False:
                return response[currency]['Value']
            elif self.format == 'value' and self.diff == True:
                diffrence = response[currency]['Value'] - response[currency]['Previous']
                return diffrence
                
        return 'Error'
    
    def eur(self):
        return self.make_format('EUR')
    
    def usd(self):
        return self.make_format('USD')
    
    def brl(self):
        return self.make_format('BRL')

In [22]:
r = Rate(diff_ = True)

In [23]:
r.exchange_rates()

{'AUD': {'ID': 'R01010',
  'NumCode': '036',
  'CharCode': 'AUD',
  'Nominal': 1,
  'Name': 'Австралийский доллар',
  'Value': 56.8918,
  'Previous': 57.1016},
 'AZN': {'ID': 'R01020A',
  'NumCode': '944',
  'CharCode': 'AZN',
  'Nominal': 1,
  'Name': 'Азербайджанский манат',
  'Value': 43.5782,
  'Previous': 43.7104},
 'GBP': {'ID': 'R01035',
  'NumCode': '826',
  'CharCode': 'GBP',
  'Nominal': 1,
  'Name': 'Фунт стерлингов Соединенного королевства',
  'Value': 102.8258,
  'Previous': 103.0562},
 'AMD': {'ID': 'R01060',
  'NumCode': '051',
  'CharCode': 'AMD',
  'Nominal': 100,
  'Name': 'Армянских драмов',
  'Value': 14.0559,
  'Previous': 14.1331},
 'BYN': {'ID': 'R01090B',
  'NumCode': '933',
  'CharCode': 'BYN',
  'Nominal': 1,
  'Name': 'Белорусский рубль',
  'Value': 28.4362,
  'Previous': 28.4809},
 'BGN': {'ID': 'R01100',
  'NumCode': '975',
  'CharCode': 'BGN',
  'Nominal': 1,
  'Name': 'Болгарский лев',
  'Value': 44.9486,
  'Previous': 45.1124},
 'BRL': {'ID': 'R01115',
  'NumCode': '986',
  'CharCode': 'BRL',
  'Nominal': 1,
  'Name': 'Бразильский реал',
  'Value': 12.759,
  'Previous': 12.639},
 'HUF': {'ID': 'R01135',
  'NumCode': '348',
  'CharCode': 'HUF',
  'Nominal': 100,
  'Name': 'Венгерских форинтов',
  'Value': 23.959,
  'Previous': 24.0551},
 'HKD': {'ID': 'R01200',
  'NumCode': '344',
  'CharCode': 'HKD',
  'Nominal': 10,
  'Name': 'Гонконгских долларов',
  'Value': 95.3599,
  'Previous': 95.6111},
 'DKK': {'ID': 'R01215',
  'NumCode': '208',
  'CharCode': 'DKK',
  'Nominal': 1,
  'Name': 'Датская крона',
  'Value': 11.8223,
  'Previous': 11.8648},
 'USD': {'ID': 'R01235',
  'NumCode': '840',
  'CharCode': 'USD',
  'Nominal': 1,
  'Name': 'Доллар США',
  'Value': 74.0393,
  'Previous': 74.264},
 'EUR': {'ID': 'R01239',
  'NumCode': '978',
  'CharCode': 'EUR',
  'Nominal': 1,
  'Name': 'Евро',
  'Value': 87.9587,
  'Previous': 88.1736},
 'INR': {'ID': 'R01270',
  'NumCode': '356',
  'CharCode': 'INR',
  'Nominal': 10,
  'Name': 'Индийских рупий',
  'Value': 10.1365,
  'Previous': 10.1738},
 'KZT': {'ID': 'R01335',
  'NumCode': '398',
  'CharCode': 'KZT',
  'Nominal': 100,
  'Name': 'Казахстанских тенге',
  'Value': 17.6016,
  'Previous': 17.6908},
 'CAD': {'ID': 'R01350',
  'NumCode': '124',
  'CharCode': 'CAD',
  'Nominal': 1,
  'Name': 'Канадский доллар',
  'Value': 58.4183,
  'Previous': 58.7578},
 'KGS': {'ID': 'R01370',
  'NumCode': '417',
  'CharCode': 'KGS',
  'Nominal': 100,
  'Name': 'Киргизских сомов',
  'Value': 87.2825,
  'Previous': 87.5474},
 'CNY': {'ID': 'R01375',
  'NumCode': '156',
  'CharCode': 'CNY',
  'Nominal': 1,
  'Name': 'Китайский юань',
  'Value': 11.3691,
  'Previous': 11.3935},
 'MDL': {'ID': 'R01500',
  'NumCode': '498',
  'CharCode': 'MDL',
  'Nominal': 10,
  'Name': 'Молдавских леев',
  'Value': 41.8786,
  'Previous': 42.1955},
 'NOK': {'ID': 'R01535',
  'NumCode': '578',
  'CharCode': 'NOK',
  'Nominal': 10,
  'Name': 'Норвежских крон',
  'Value': 87.1307,
  'Previous': 87.391},
 'PLN': {'ID': 'R01565',
  'NumCode': '985',
  'CharCode': 'PLN',
  'Nominal': 1,
  'Name': 'Польский злотый',
  'Value': 19.21,
  'Previous': 19.2254},
 'RON': {'ID': 'R01585F',
  'NumCode': '946',
  'CharCode': 'RON',
  'Nominal': 1,
  'Name': 'Румынский лей',
  'Value': 17.993,
  'Previous': 18.0612},
 'XDR': {'ID': 'R01589',
  'NumCode': '960',
  'CharCode': 'XDR',
  'Nominal': 1,
  'Name': 'СДР (специальные права заимствования)',
  'Value': 105.6918,
  'Previous': 105.8574},
 'SGD': {'ID': 'R01625',
  'NumCode': '702',
  'CharCode': 'SGD',
  'Nominal': 1,
  'Name': 'Сингапурский доллар',
  'Value': 54.9212,
  'Previous': 55.1452},
 'TJS': {'ID': 'R01670',
  'NumCode': '972',
  'CharCode': 'TJS',
  'Nominal': 10,
  'Name': 'Таджикских сомони',
  'Value': 64.9753,
  'Previous': 65.1724},
 'TRY': {'ID': 'R01700J',
  'NumCode': '949',
  'CharCode': 'TRY',
  'Nominal': 10,
  'Name': 'Турецких лир',
  'Value': 97.0689,
  'Previous': 96.6501},
 'TMT': {'ID': 'R01710A',
  'NumCode': '934',
  'CharCode': 'TMT',
  'Nominal': 1,
  'Name': 'Новый туркменский манат',
  'Value': 21.1843,
  'Previous': 21.2486},
 'UZS': {'ID': 'R01717',
  'NumCode': '860',
  'CharCode': 'UZS',
  'Nominal': 10000,
  'Name': 'Узбекских сумов',
  'Value': 70.5306,
  'Previous': 70.7907},
 'UAH': {'ID': 'R01720',
  'NumCode': '980',
  'CharCode': 'UAH',
  'Nominal': 10,
  'Name': 'Украинских гривен',
  'Value': 26.7712,
  'Previous': 26.7446},
 'CZK': {'ID': 'R01760',
  'NumCode': '203',
  'CharCode': 'CZK',
  'Nominal': 10,
  'Name': 'Чешских крон',
  'Value': 33.508,
  'Previous': 33.5535},
 'SEK': {'ID': 'R01770',
  'NumCode': '752',
  'CharCode': 'SEK',
  'Nominal': 10,
  'Name': 'Шведских крон',
  'Value': 86.7733,
  'Previous': 86.8311},
 'CHF': {'ID': 'R01775',
  'NumCode': '756',
  'CharCode': 'CHF',
  'Nominal': 1,
  'Name': 'Швейцарский франк',
  'Value': 79.6464,
  'Previous': 79.4607},
 'ZAR': {'ID': 'R01810',
  'NumCode': '710',
  'CharCode': 'ZAR',
  'Nominal': 10,
  'Name': 'Южноафриканских рэндов',
  'Value': 48.4833,
  'Previous': 48.2905},
 'KRW': {'ID': 'R01815',
  'NumCode': '410',
  'CharCode': 'KRW',
  'Nominal': 1000,
  'Name': 'Вон Республики Корея',
  'Value': 64.782,
  'Previous': 65.2288},
 'JPY': {'ID': 'R01820',
  'NumCode': '392',
  'CharCode': 'JPY',
  'Nominal': 100,
  'Name': 'Японских иен',
  'Value': 68.0477,
  'Previous': 68.2166}}

In [25]:
r.usd()

-0.22469999999999857

Задание 3 - тут также немного непонятно с условием задачи...

In [27]:
class Employee:
    def __init__(self, name, seniority):
        self.name = name;
        self.seniority = seniority;
        self.grade = 4;
        
    def grade_up(self):
        self.grade +=1;
    
    def publish_grade(self):
        print(self.name, self.grade)
        
class Designer(Employee):
    def __init__(self, name, seniority):
        super().__init__(name, seniority)
        
    def check_if_it_is_time_for_upgrade(self):
        # для каждой аккредитации увеличиваем счетчик на 1
        # пока считаем, что все разработчики проходят аккредитацию
        self.seniority += 1
        
        # условие повышения сотрудника из презентации
        if self.seniority % 7 == 0:
            self.grade_up()
        
        # публикация результатов
        return self.publish_grade()

In [28]:
sam = Designer('Sammy', 0)

In [30]:
for i in range(40):
    sam.check_if_it_is_time_for_upgrade()

Sammy 7
Sammy 7
Sammy 7
Sammy 7
Sammy 7
Sammy 7
Sammy 7
Sammy 8
Sammy 8
Sammy 8
Sammy 8
Sammy 8
Sammy 8
Sammy 8
Sammy 9
Sammy 9
Sammy 9
Sammy 9
Sammy 9
Sammy 9
Sammy 9
Sammy 10
Sammy 10
Sammy 10
Sammy 10
Sammy 10
Sammy 10
Sammy 10
Sammy 11
Sammy 11
Sammy 11
Sammy 11
Sammy 11
Sammy 11
Sammy 11
Sammy 12
Sammy 12
Sammy 12
Sammy 12
Sammy 12